#!/usr/bin/env ruby

# frozen_string_literal: true

$stdout.sync = true

require "yaml"
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "phlex", "~> 1.11"
  gem "logger"
  gem "filewatcher"
  gem "webrick"
end

require_relative "src/website"

website = Website.new

case ARGV.first&.strip
when "serve"
  website.serve
when "generate"
  website.generate
else
  process = fork { website.serve }
  Process.detach(process)

  website.generate

  Filewatcher.new(Website::WATCHED_FILES).watch do |filename, event|
    website.generate
  rescue e
    puts e.backtrace
    puts "❌ #{e.message}"
  end
end
