name: 'Deploy static content to Github Pages'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: 'read'
  pages: 'write'
  id-token: 'write'

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Setup ruby'
        uses: 'ruby/setup-ruby@v1'
        with:
          ruby-version: ".tool-versions" # Use ruby version in `.tool-versions` file
          bundler-cache: true # Auto run `bundle install`

      - name: 'Generate website'
        run: './run generate'

      - name: 'Upload www artifact'
        uses: 'actions/upload-pages-artifact@v3'
        with:
          name: 'www ${{ github.sha }}'
          path: "./www"

  deploy:
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - name: 'Deploy to GitHub Pages'
        id: 'deployment'
        uses: 'actions/deploy-pages@v4'
        with:
          artifact_name: 'www ${{ github.sha }}'
